name: Android CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@main
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: List files in working directory
        run: ls -R
          
      - name: Grant execute permission for gradlew
        run: chmod +x easycontrol/gradlew

      - name: Build with Gradle
        run: easycontrol/gradlew build --warning-mode all

      - name: Package APKs
        run: zip -r artifacts.zip app/build/outputs/**/*.apk

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: artifacts.zip
